name: Sync to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: 'PxPQpkBdPRsjkP40GePMNCr6FlTgVjrU'

          # [OPTIONAL CONFIG]
          oas-file-path: './openapi.yaml'
          api-version: 'v1.0.0'
