name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: 4nDBAUF4nFwsgD1vxmF3E0eBfaxA4HP8

          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './test.yml'
          api-version: 'v1.0.0'